# Generated by Django 5.2.16 on 2026-08-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0002_orden_usuario_direccion_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
